FORMAT: 1A
HOST: http://bingtastic-oomlaut.rhcloud.com/api

# Bingtastic API

The Bingtastic service provides usable data for developers to roll their own
[Bing Rewards](http://go.microsoft.com/?linkid=9778718&rrid=_ad8ea4a6-b009-6b60-1c54-667a72de00e5) applications.

Data can be accessed either via `curl` or `jsonp`

## cURL Example

    curl "http://bingtastic-oomlaut.rhcloud.com/api/?respo curl "http://bingtastic-oomlaut.rhcloud.com/api/?response=json"

## JSONp Example

    &lt;script&gt;
        'use strict';
        BingMe = function(data){
            /* &hellip; do something with the data returned &hellip; */
        };
    &lt;/script&gt;

    &lt;script src="//bingtastic-oomlaut.rhcloud.com/api/?bings=60&amp;categories=images,videos"&gt;&lt;/script&gt;
    
# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
